### ISSUE TITLE
Support for Deep Linking

### ISSUE THREAD

**Issue by BradRem** [nbellocam/Angular2ASPNETCoreBaseApp#2]
I believe a fundamental experience is the ability to handle deep linking, which is where the user clicks on shortcut or types in a URL such as `http://localhost/app/feature/10` and the website will go directly to that page.  A URL entered this way (or a page that is reloaded by the user) will be handled by the server, instead of Angular.  Since the server won't find a Controller/Action, it will 404.

I'd like to suggest this base template include at least the code to allow deep linking and page refreshes.

**Comment by nbellocam** [comment]
Thanks, my initial idea was to keep this as a super basic template, without routing or other kind of modules/configurations. I plan to create a new repository/branch with a few more configurations.

Let me think about it, and I will merge the PR https://github.com/nbellocam/Angular2ASPNETCoreBaseApp/pull/3 based on that.

By the way, thanks for the feedback and PR, this is really useful and I think the same, that's why I want to think whats the best approach to show that.

**Comment by nbellocam** [comment]
I merged your updates inside the [routing-sample](https://github.com/nbellocam/Angular2ASPNETCoreBaseApp/tree/routing-sample) branch.

However, note that I updated the solution to show different routes, use a default route and also I added the Microsoft.AspNet.SpaServices, in order to avoid issues with missing assets.

Thanks for your feedback and your PR!
